INSERT INTO dulcesrecetas.recetas ( created_at, updated_at, nombre, img, continente, descripcion, alergenos, 
dificultad, tiempo, calorias, npersonas, ingreCantidad, procedimiento,  detalles ) VALUES (
'2022-05-05 22:53:45','2022-05-05 22:53:45',
'Tarta de queso y cerezas',
'',
'Europa',
'Esta Tarta de queso y cerezas es una de las más ricas que he probado, una tarta de queso muy suave, con una base de galleta, nueces y mantequilla y una cobertura de cerezas que quita el sentido, en este caso usaremos picotas del Jerte.',
'Huevos',
'principiante',
20, 1000, 4,
'30 galletas, 70 gramos de mantequilla, 50 gramos de nueces, 600 gramos de queso crema para untar, 
3 cucharadas de harina fina de Maíz, 7 huevos, 1 yogur griego, 200 gramos de azúcar, 500 ml de nata líquida para montar, 
400 gramos de cerezas, 2 cucharadas de azúcar, Agua',
'Trituramos las galletas con las nueces y la mantequilla, Y lo ponemos en el molde, aunque es desmontable, he puesto papel de horno en la base, 
Con el dorso de una cuchara extendemos bien la mezcla, Horneamos unos 10 minutos a 180º C, 
Ponemos los huevos en un recipiente, Añadimos el azúcar y lo batimos todo, Incorporamos la maizena, el queso crema, la nata y el yogur, 
Y lo batimos todo muy bien, Vertemos esta mezcla sobre la base ya horneada. Metemos en el horno, a 200º unos 10 minutos, pasado el tiempo bajamos la temperatura a 180º unos 50 minutos más. Si véis que la superficie se dora en exceso podéis taparla con papel aluminio o ponerla en la ranura inferior, 
Mientras la tarta está en el horno, vamos a preparar la cobertura. Deshuesamos las cerezas y las ponemos en un cazo, reservamos algunas, 
Añadimos un par de cucharadas de azúcar y un poco de agua, Dejamos cocinar a fuego muy suave unos 20 o 30 minutos, hasta que quede así. Enrique lo tritura todo y luego cuela, pero yo he preferido dejar la fruta así, 
Añadimos unas cuantas cerezas deshuesadas y mezclamos, con el calor residual quedan perfectas, Sacamos la tarta del horno y desmoldamos, 
cubrimos con la cobertura de cerezas y metemos en el frigorífico y una vez fría, Servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Tarta de requesón y almendra',
'',
'Europa',
'Una mezcla de tarta de queso y tarta de almendra realmente deliciosa.',
'Huevos',
'principiante',
40, 1000, 4,
'4 huevos, 200 g de azúcar, 250 g almendra molida, Ralladura de 2 limones, 350 g de requesón de cabra,
1 cucharada de anís dulce, 30 g de aceite de oliva virgen extra, Almendra laminada, 1 cucharada de azúcar',
'Ponemos los huevos y el azúcar en un recipiente y batimos, Incorporamos la almendra molida y ralladura de los dos limonesy el requesón,
Añadimos el aceite de oliva virgen extra de la variedad royal de Aceites Cazorla,
Y el anís dulce y lo batimos y mezclamos todo, Vertemos en un molde y cubrimos la superficie con las almendras laminadas,
Y una o dos cucharadas de azúcar por encima listo para entrar en el horno que estará precalentado a 180º C 30 min,
Desmoldamos y dejamos enfriar servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Muffins superchocolatosos',
'',
'Europa',
'Muffins que como bien indica el nombre de esta receta con mucho sabor a chocolate, son muy esponjosos y jugosos',
'Huevos',
'Principiante',
30, 1500, 4,
'2 huevos,
150 g de yogurt natural,
125 ml de buttermilch,
125 ml aceite de oliva virgen extra,
250 g de harina,
200 g de azúcar moreno,
50 g de azúcar blanca,
50 g de cacao en polvo sin azúcar,
1 cucharadita de levadura química (polvos de hornear),
1 taza gotas de chocolate',
'Ponemos los huevos y todos los ingredientes líquidos en un recipiente,
Si no tenéis buttermilch ponéis 125ml de leche y batimos todo con varilla o batidora,
Por otro lado ponemos en un recipiente todos los ingredientes secos, harina, azúcar, cacao, levadura y mezclamos,
Vamos añadiendo cucharada a cucharada esta mezcla mientras continuamos batiendo,
Añadimos las gotas o pepitas de chocolate y reservamos algunas para el final, 
Ponemos las cápsulas de papel en un molde rígido, llenamos dejando un dedo,
Metemos en el horno, a 180º C unos 20 minutos,
Sacamos del horno y en este momento podéis ponerle más pepitas de chocolate por encima como están calientes se fundirán,
Desmoldamos y dejamos enfriar servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Bizcocho de manzana y queso',
'',
'Europa',
'Un bizcocho riquísimo perfecto para el desayuno o la merienda, gustará a toda la familia.',
'Huevos',
'Principiante',
60, 1800, 4,
'4 huevos grandes,
150 g de azúcar,
250 g de queso mascarpone (1 tarrina),
2 manzanas (relleno),
300 g de harina,
Una cucharadita de canela molida,
Un sobre de levadura química o polvos de hornear (16 g),
1 o 2 manzanas (en láminas),
1 cucharada de azúcar,
2 cucharadas mermelada de albaricoque',
'Ponemos en un recipiente los huevos junto con el azúcar y el queso mascarpone y batimos,
Incorporamos el harina, la levadura, la canela molida y mezclamos bien hasta que esté todo integrado
Añadimos dos manzanas picadas y mexclamos si os queda muy densa podeis incorporar 1 o 2 cucharadas de leche,
Vertemos la mezcla en un molde alisamos la superficie y cubrimos con láminas de manzana espolvoreada con azúcar,
Con el horno precalentado a 180º C horneamos 45 minutos,
Aún en caliente pincelamos la superficie con mermelada de albaricoque,
Desmoldamos y dejamos enfriar servir y disfrutar
',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Tarta de queso y turrón',
'',
'América',
'Muy suave y cremosa, con el sabor del turrón, es una delicia perfecta para rematar cualquier comida de fiesta',
'Huevos',
'Principiante',
45, 2000, 4,
'3 huevos,
1 lata pequeña de leche condensada,
1 yogur natural,
400 g de queso crema para untar,
200 g de turrón de Jijona,
30 g de harina fina de maíz,
Almendras y azúcar glass para decorar',
'Ponemos todos los ingredientes en un recipiente y tituramos todo con la batidora,
Vertemos en un molde previamente engrasado,
Metemos en el horno a 180º C unos 35-40 minutos,
podemos añadir azúcar glass y almendra picada por encima,
Desmoldamos y dejamos enfriar servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Bizcochos en sandwichera',
'',
'Europa',
'Una receta que arrasa en internet y que en mi casa triunfa, es tan fácil de hacer que la hacen hasta los niños',
'Huevos',
'Principiante',
15, 600, 2,
'3 huevos,
180 gr de azúcar,
1 yogur natural,
110 ml de aceite de oliva virgen extra,
Ralladura de 1 limón,
250 gr de harina,
1 sobre de levadura química (16 gr) o polvos de hornear,
Azúcar glass y canela molida',
'Ponemos los huevos el azúcar en un cuenco amplio y mezclamos,
Añadimos el yogur el aceite la rayadura de limón y mezclamos,
Tamizamos encima la harina y la levadura mezclando,
Añadimos 2 cucharadas de masa a la sandwichera precalentada y contamos 3 minutos aprox,
Desmoldamos y dejamos enfriar servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Bizcocho de limón y arándanos',
'',
'América del Norte',
'.',
'Huevos',
'Principiante',
45, 950, 4,
'3 huevos,
180 gr de azúcar,
180 ml de aceite de oliva virgen extra,
1 yogur natural de cabra,
75 ml de zumo de limón,
Ralladura de dos limones pequeños o 1 grande,
250 gr de harina,
1 sobre de levadura química, polvos de hornear o impulsor,
125 gr de arándanos,
Azúcar glass',
'Ponemos en un recipiente los huevos el azúcar y batimos varios minutos,
Añadimos el aceite de oliva virgen extra mientras continuamos batiendo,
Añadimos la ralladura el jugo de limón y mezclamos,
Y por último harina y levadura tamizado y mezclamos bien,
Ponemos los arándanos en la superficie y metemos al horno precalentado a 180º C 35 minutos,
Desmoldamos y dejamos enfriar servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Tarta de zanahoria',
'',
'Europa',
'Pastel originario de Europa que fue llevado hasta Estados Unidos por los emigrantes y que allí se ha convertido en uno de sus mejores postres',
'Huevos',
'Intermedio',
50, 800, 4,
'250 gr de zanahorias (ya peladas y limpias),
60 gr de nueces,
4 huevos,
150 ml de aceite de oliva virgen extra,
200 gr de azúcar moreno,
1 cucharadita de jengibre molido,
1 cucharadita de canela molida,
250 gr de harina de repostería,
2 sobres (dobles) de gasificante de repostería o 1 un sobre de levadura química,
350 gr de nata líquida para montar,
300 gr de queso crema de untar,
50 gr de mantequilla,
100 gr de azúcar glass',
'Troceamos las zanahorias y las trituramos junto con las nueces,
En un recipiente ponemos los huevos el azúcar y batimos unos minutos incorporando el aceite poco a poco,
Añadimos las zanahorias y las nueces junto con las especias la harina y el gasificante o la levadura,
Mezclamos bien con una espátula y vertemos la masa en un molde engrasado,
Metemos en el horno precalentado a 170 º unos 30-35 minutos,
Desmoldamos y dejamos enfriar,
Ahora vamos con el relleno y cobertura,
Batimos la nata sola y batimos el queso crema con el azúcar glass y la mantequilla,
Mezclamos ambas preparaciones y cubrimos el pastel,
Servir y disfrutar',
'Comparte con tus amigos si te gustó.'),

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'Tiramisú con requesón',
'',
'Europa',
'Tiramisú italiano, pero sustiyendo el queso marcarpone tradicional de esta receta por el requesón',
'Huevos',
'principiante',
20, 600, 4,
'Café,
2 cucharadas de Amaretto,
2 huevos,
3 cucharadas de azúcar,
250 gr de requesón de cabra,
250 ml de nata líquida para montar,
Savoiardi,
Cacao en polvo sin azúcar',
'Hacer café podéis hacerlo descafeinado le echamos un chorrito Disaronno Amaretto. Lo dejamos en un recipiente,
Montamos las claras de huevo. Reservamos. Montamos la nata,
En un recipiente ponemos el requesón las yemas de huevo el azúcar y batimos,
Incorporamos la nata y las claras a la mezcla anterior,
Montamos el tiramisú mojamos los savoiardi bizcochos secos alargados en el café,
Y cubrimos con ellos la base de un molde extendemos la mitad de la crema,
Ponemos otra capa de savoiardi mojados en el café extendemos el resto de crema,
Espolvoreamos toda la superficie con cacao en polvo sin azúcar,
Servir y disfrutar',
'Comparte con tus amigos si te gustó.')
;

  // plantilla

('2022-05-05 22:53:45','2022-05-05 22:53:45',
'nombre',
'',
'Europa',
'descripcion',
'alergenos',
'principiante',
tiempo, cal,
'ingredientes',
'procedimiento',
'Comparte con tus amigos si te gustó.')